Add Upcloud VolumeSnapshotClass
elastisys/kubespray pull request #16
Opened 2024-06-20 12:04 UTC by robinelastisys

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2024-06-25 09:00 UTC, Elias-elastisys submitted a review, later dismissed
Is it possible to add templating so that we can configure labels and annotations?

We want to have these values for this, but it should probably not be hardcoded in kubespray.
```yaml
annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
labels:
    velero.io/csi-volumesnapshot-class: "true"
```

2024-06-26 08:42 UTC, simonklb requested changes

2024-06-26 08:42 UTC, simonklb commented on roles/kubernetes-apps/csi_driver/upcloud/templates/upcloud-csi-setup.yml.j2
> +  {% endif %}
The indentation looks off here compare to the rest of the file and the yaml doc separator should also be conditional.

2024-07-11 13:21 UTC, Pavan-Gunda commented
I need to get this merged first so i can later merge https://github.com/elastisys/compliantkubernetes-kubespray/pull/367/files but with kubespray submodule cherry-picked to have [this](https://github.com/kubernetes-sigs/kubespray/commit/cb9d5906bb9bd0b075dbb5651ae9d6cb7cb26b7e) and this PR.

2024-07-11 14:48 UTC, Ajarmar approved these changes

2024-07-12 08:27 UTC, merged